spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        https://docs.spring.io/spring-boot/docs/3.1.7/reference/html/data.html#data.sql.jpa-and-spring-data.creating-and-dropping

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace